blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://discord.com/invite/u7QXUgPcqr
    about: Join our Discord community for general discussions, questions, and support.
